### ISSUE TITLE
A promblem about using minigpt4

### ISSUE THREAD

**Issue by running-alpaca** [AdaCheng/EgoThink#15]
1.In the file EgoThink/models/minigpt4_legacy/minigpt4_eval.yaml, it has prompt_path: "VLMs/MiniGPT-4/prompts/alignment.txt", where could I find or download this file? What is the content of this file?
2.Under the folder "models", the file "test_minigpt4.py" has not add in the "__init__.py". Could I use the follow code to add it?
```
    elif model_name == 'minigpt4':
        from .test_minigpt4 import TestMiniGPT4
        return TestMiniGPT4(device=device)
```

**Comment by zhichengg** [comment]
1. This is the alignment.txt file in the minigpt-4 repo. You can find it at https://github.com/Vision-CAIR/MiniGPT-4/blob/main/prompts/alignment.txt. 
2. Of course you can! And we will add minigpt-4 recently.

**Comment by running-alpaca** [comment]
Thank you for your help! After download this file, I have successfully completed the experiment of minigpt4 based on vicuna7b. But still can't run minigpt4 based on llama2. It seems that the relevant configuration files are missing. The code can't identify the model_type of pretrain_llama2.
If I complete the relevant settings, there is something wrong with the llama. It shows as: RuntimeError: probability tensor contains either inf, nan or element < 0.
Hope you could add minigpt-4 completely，thank you！

**Comment by zhichengg** [comment]
Hi, 

This is probably because the minigpt4-legacy codes are too old and at that time there was no minigpt4 based on llama2.  I have updated the codes using the new minigpt-4 repo. Please checkout the new codes at https://github.com/AdaCheng/EgoThink/tree/main/models/minigpt4.

Note that I have not implemented minigpt-4 with llama 2 and minigpt-v2. But it should take too much effort to modify the configurations and the probably a little bit of inference codes with the help of minigpt-4 repo (https://github.com/Vision-CAIR/MiniGPT-4/tree/main).

**Comment by running-alpaca** [comment]
Thank you for your reply! I'll try the now codes later!
